### PR TITLE
[MirAL] Implement a "no active window" state

### LINKED ISSUE #225: App spread closes when the first app in the list is closed
## Device
Nexus 5
Edge/Devel

## Steps to reproduce
1. Open at least 3 apps.
2. Open the app spread (long swipe from the right)
3. Close the right-most app in the spread (swipe up or down)
4. Close the left-most app in the spread.

## Expected Behavior
The right-most app is closed and removed from the spread.
The left-most app is closed and removed from the spread.
The app spread is still displayed and open after closing the apps.

## Actual Behavior
The right-most app is closed and removed from the spread.
The left-most app is closed and also closes the app spread and focuses on the next app in the spread from the left.

### PR DESCRIPTION
**Pull request by peat-psuwit**
When setting the active window to a null window, mru_active_windows
won't be updated. This commit add the `allow_active_window` flag which
will be false when a null window is set, disabling the active window.

This is used by Lomiri during spreads and other effects and animations.

Co-authored-by: Alan Griffiths <alan@octopull.co.uk>

This PR comes with Jenkinsfile update.

Fixes ubports/unity8#225.

### CODE REVIEW

**Comment by peat-psuwit** [comment]
Well, it crashes unity8 when a trusted surface is closed. Will investigate further.

**Comment by Flohack74** [comment]
On an unrelated note, I still have situations in TELEports when it thinks that the App is still suspended... It got better with the other commit, but is not entirely gone.

**Comment by peat-psuwit** [comment]
The crash is fixed. Now ready for review.

File: src/miral/basic_window_manager.cpp [hunk 1]
```diff
@@ -511,7 +511,17 @@ void miral::BasicWindowManager::force_close(Window const& window)
 
 auto miral::BasicWindowManager::active_window() const -> Window
 {
-    return mru_active_windows.top();
+    auto const focussed_surface = focus_controller->focused_surface();
```
Comment (Flohack74) [inline src/miral/basic_window_manager.cpp]: Small typo, it would be focused_surface in English :)

**Review by Flohack74 — CHANGES_REQUESTED** [review]

File: src/miral/basic_window_manager.cpp (hunk 1 above)
Comment (peat-psuwit) [reply src/miral/basic_window_manager.cpp]: Well, this code is copied from another code in the same file. Also, "focussed" is kind of a valid spelling in British English (and Canonical is a UK-based company so... :) ).

https://en.wiktionary.org/wiki/focussed

Comment (Flohack74) [reply src/miral/basic_window_manager.cpp]: Its just odd that in the same line of code you have 2 spellings... If you want to keep it though I wont block it ofc.

Comment (peat-psuwit) [reply src/miral/basic_window_manager.cpp]: Oh, didn't notice that there're 2 spellings in the same line. Then I'll fix it.

**Comment by mariogrip** [comment]
Has this been proposed upstream?

Ping @AlanGriffiths

**Comment by AlanGriffiths** [comment]
> Has this been proposed upstream?
> 
> Ping @AlanGriffiths

Quick answer:

1. It hasn't been proposed. 
2. It doesn't look stupid (apart from mixing Jenkins stuff with code), but I've not got my head sufficiently around the issue to know if it's right.

**Comment by peat-psuwit** [comment]
This PR gets updated with the suggested fix from Alan which seems to be cleaner.

**Comment by peat-psuwit** [comment]
Ok. Confirmed that this actually fixes the issue. Ready to be merged!

**Review by Flohack74 — APPROVED** [review]

**Review by UniversalSuperBox — APPROVED** [review]
